### PR TITLE
Fix broken link

### PR DESCRIPTION
**Pull request by sonicdoe**
You can find this link on [guides.rubygems.org/specification-reference/](http://guides.rubygems.org/specification-reference/) in the first paragraph.

### CODE REVIEW

**Comment by segiddins** [comment]
Maybe this should link to http://guides.rubygems.org/what-is-a-gem/

**Comment by sonicdoe** [comment]
I thought about this too, however, almost none of the other guides link the word “gem”.

**Comment by colby-swandale** [comment]
@sonicdoe we would prefer if it continued to link to the relevant source, I agree that it should now link to `http://guides.rubygems.org/what-is-a-gem/` instead. The other guides not linking appropriately is something that needs to be improved upon.

**Comment by sonicdoe** [comment]
Updated.

**Pull request merged**
