### PR TITLE
Replace twitter gem as signed gem example by metric_fu since twitter gem is not signed anymore.

### PR DESCRIPTION
**Pull request by simi**
ref https://github.com/sferik/twitter/commit/0291149557b625302ea14b2e61290aff132a64d8

:thinking: we can also swap it to metric_fu for example since that one is well known and signed gem

### CODE REVIEW

**Comment by sonalkr132** [comment]
> we can also swap it to metric_fu 

yes please

**Comment by abitrolly** [comment]
Needs rebasing.

**Comment by simi** [comment]
@abitrolly @sonalkr132 updated to metric_fu.

**Comment by sonalkr132** [comment]
Thanks :+1:

**Comment by bf4** [comment]
fun fact, I'm an (inactive) maintainer of metric-fu (and I might have written this section of the guide ;) and recently told the new maintainer it would be fine to no longer sign the gem since it's not really used.

I'd propose we revise this page to no recommend it and link to a known signing *version* of a gem, even if it's no longer being released signed

**Comment by deivid-rodriguez** [comment]
I also found https://github.com/mongodb/bson-ruby recently that seems to be signed too, in case we want to switch to that :man_shrugging:.

**Pull request merged**
