### PR TITLE
Change mfa status indicators on MFA opt-in page

### PR DESCRIPTION
**Pull request by kevinlinxc**
After https://github.com/rubygems/rubygems.org/pull/3079 is merged, the [opt-in](https://guides.rubygems.org/mfa-requirement-opt-in/) page will need to be updated to reflect the new indicators, which is what I've done here. 
Also, the old file was small/blurry, but maybe that was to reduce file size?

### CODE REVIEW

**Comment by kevinlinxc** [comment]
image

**Review by bettymakes — COMMENTED** [review]
I'd recommend revising this image to a smaller size, since the context it'll be used in will likely never need it to be that high of a resolution. 

As an aside, my personal boundary for image assets on the web is ~300kb (depending on usage). This seems to be a bit over. I think reducing the size by a bit would be a good call.

**Comment by kevinlinxc** [comment]
@bettymakes reduced the size. I found the relationship between width x height surprisingly non linear with file size, although I suppose at this small of a file size metadata takes up a decent amount.

**Comment by sonalkr132** [comment]
Thank you.

**Pull request merged**
