### PR TITLE
remove See also from require_paths=

### PR DESCRIPTION
**Pull request by sonalkr132**
Should `require_path` be pointing to something instead?

### CODE REVIEW

**Comment by sonalkr132** [comment]
Someone here doesn't have their trailing white-space highlight on.

**Comment by dwradcliffe** [comment]
This file is generated automatically.

**Comment by bf4** [comment]
@sonalkr132 in order change this page, you must edit the comments in rubygems specification (see https://github.com/rubygems/rubygems/pull/713#issue-22813759 for how I've done it before)

**Comment by sonalkr132** [comment]
Thanks @bf4  @dwradcliffe. I am closing this. I will send PR to rubygems.

**Pull request closed without merging**
