### PR TITLE
Fix misalignment in gem install on Command Reference

### LINKED ISSUE #223: Misalignment in gem install on Command Reference
https://guides.rubygems.org/command-reference/#gem-install

We are seeing as follows:

- -​-minimal-deps - Don’t upgrade any dependencies that already meet version requirements
- 　
    - -​-[no-]post-install-message Print post install message
- -g, -​-file [FILE] - Read from a gem dependencies API file and install the listed gems

because there are two spaces between option string and description for `--[no-]post-install-message`:

```bash
$ docker run --rm ruby:2.6 gem install --help | head -50 | tail -5
        --minimal-deps               Don't upgrade any dependencies that already
                                     meet version requirements
        --[no-]post-install-message  Print post install message
    -g, --file [FILE]                Read from a gem dependencies API file and
                                     install the listed gems
```

### PR DESCRIPTION
**Pull request by tnir**
Fix misalignment in gem install on Command Reference by fixing `helpline` parser.

Closes #223

### CODE REVIEW

**Comment by tnir** [comment]
Blocker #225 was resolved so ready to get reviewed.

**Comment by tnir** [comment]
It might be convenient to use https://github.com/rubygems/guides/pull/226/files?w=1 for the review.

**Comment by segiddins** [comment]
Looks great, thanks!
@bundlerbot r+

**Comment by tnir** [comment]
@segiddins Thanks 😀

**Comment by tnir** [comment]
@segiddins Thanks. When will this (and #225) deploy to the production? https://guides.rubygems.org/command-reference/

**Pull request merged**
