### PR TITLE
Add AWS SigV4 documentation

### PR DESCRIPTION
**Pull request by bronzdoc**
Adds https://github.com/rubygems/rubygems/pull/2807 documentation

cc @apakulov-stripe

### CODE REVIEW

**Comment by apakulov-stripe** [comment]
@bronzdoc do you mind if re-format my wording from https://github.com/rubygems/rubygems/pull/2807 and will send a PR your way? (Since I don't have have a permission to create a branch in this repo).

**Comment by bronzdoc** [comment]
No problem at all @apakulov-stripe! please do :) thanks so much!

**Comment by apakulov-stripe** [comment]
@bronzdoc created a separate PR: https://github.com/rubygems/guides/pull/240
I think we close this one.

**Comment by bronzdoc** [comment]
Closing in favor of https://github.com/rubygems/guides/pull/240

**Pull request closed without merging**
